version: '3'
services:
  db:
    image: "postgres:9.6"
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - 5432:5432
        
    healthcheck:
      test: ["CMD-SHELL", "sleep 3 && pg_isready -U postgres"]
  app:
    build: "."
    environment:
      API_ENDPOINT: ${API_ENDPOINT}
      API_KEY: ${API_KEY}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
    depends_on:
      - "db"
    volumes:
      - "./src:/src"